version: "3"
services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - 9090:9090
  grafana:
    image: grafana/grafana
    restart: always
    ports:
    - 3000:3000
    links:
    - prometheus
    volumes:
    - ./grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_USERS_ALLOW_SIGN_UP: "true"
  jaeger:
    image: jaegertracing/all-in-one:1.6
    restart: always
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686
    - 14268:14268
    - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  nginx:
    image: nginx:latest
    restart: always
    ports:
    - 80:80
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./web:/var/www/html
    links:
    - prometheus
    - grafana
    - jaeger
