{
 "title": "netdata",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(netdata_services_cpu_percent_average,instance)"
   },
   {
    "name": "ne_instance",
    "query": "label_values(node_filefd_maximum,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "netdata_services_cpu_percent_average{instance=~\"$instance\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Memory ($instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "repeat": "instance",
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_services_mem_usage_MB_average{instance=~\"$instance\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "bandwidth ($instance)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "repeat": "instance",
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "netdata_net_net_kilobits_persec_average{instance=~\"$instance\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "file discriptors ($ne_instance)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "repeat": "ne_instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_maximum{instance=~\"$ne_instance\"}",
     "legendFormat": "maximum"
    },
    {
     "expr": "node_filefd_allocated{instance=~\"$ne_instance\"}",
     "legendFormat": "allocated"
    }
   ]
  }
 ]
}